name: 'Install Using PyPI'
description: 'Setup environment and install using the PyPI-based toolchain'
inputs:
  need-cartopy:
    description: 'Whether Cartopy is needed'
    required: true
    default: 'true'
  type:
    description: 'Whether test or doc build'
    required: true
  version-file:
    description: 'Name of the version file to use for installation'
    required: true
    default: 'requirements.txt'
  python-version:
    description: 'What version of Python to use'
    required: true

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          ci/${{ inputs.type }}_requirements.txt
          ci/${{ inputs.version-file }}

    # This installs the stuff needed to build and install Shapely and CartoPy from source.
    - name: Install CartoPy build dependencies
      if: ${{ inputs.need-cartopy == 'true' }}
      shell: bash
      run: sudo apt-get install libgeos-dev

    - name: Disable Shapely Wheels
      shell: bash
      run: echo "PIP_NO_BINARY=shapely" >> $GITHUB_ENV

    - name: Install dependencies
      shell: bash
      run: python -m pip install -r ci/${{ inputs.type }}_requirements.txt -c ci/${{ inputs.version-file }}

    - name: Install extra dependencies
      if: ${{ inputs.need-cartopy == 'true' }}
      shell: bash
      run: python -m pip install -r ci/extra_requirements.txt -c ci/${{ inputs.version-file }}

    - name: Download Cartopy Maps
      if: ${{ inputs.need-cartopy == 'true' }}
      shell: bash
      run: ci/download_cartopy_maps.py

    - name: Install
      shell: bash
      run: python -m pip install -c ci/${{ inputs.version-file }} .
