engines:
#  duplication:
#    enabled: true
#    config:
#      languages:
#      - python
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
  radon:
    enabled: true

ratings:
  paths:
  - "**/*.py"

exclude_paths:
- "versioneer.py"
- "metpy/_version.py"
- "metpy/io/nexrad_msgs/msg*.py"
- "docs/**/*"
- "examples/notebooks/*"
