coverage:
  status:
    patch:
      default:
        target: '80'
    project:
      library:
        target: auto
        threshold: 0.1%
        paths:
          - "src/metpy/.*"

      tests:
        target: 100%
        paths:
          - "tests/.*"
          - "src/metpy/testing.py"

  notify:
    gitter:
      default:
        url: "https://webhooks.gitter.im/e/301b8fd7792e1a48b034"

comment: off
