ignore-paths:
  - doc
  - build
  - metpy/_version.py
  - examples
  - tutorials

max-line-length: 95

pylint:
  disable:
    - unbalanced-tuple-unpacking

pep8:
  full: true
  disable: F999

pyroma:
  run: true

dodgy:
  run: true

python-targets:
  - 2
  - 3
