codecov:
  notify:
    require_ci_to_pass: no

coverage:
  status:
    patch:
      default:
        target: '80'
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure
    project:
      default:
        target: auto
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure

comment: off
