name: 'Install Using Conda'
description: 'Setup environment and install using a Conda-based toolchain'
inputs:
  type:
    description: 'Whether test or doc build'
    required: true
  python-version:
    description: 'What version of Python to use'
    required: true
runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: mamba-org/provision-with-micromamba@v14
      with:
        environment-file: false
        environment-name: CI
        extra-specs: python=${{ inputs.python-version }}
        channels: conda-forge/label/testing,conda-forge
        cache-env: true
        cache-env-key: mamba-${{ inputs.type }}-${{ runner.os }}-${{ inputs.python-version}}-${{ hashFiles('ci/*') }}

    - name: Install dependencies
      shell: bash -l {0}
      run: micromamba install --quiet --yes --file ci/${{ inputs.type }}_requirements.txt --file ci/extra_requirements.txt --file ci/requirements.txt

    - name: Download Cartopy Maps
      shell: bash -l {0}
      run: ci/download_cartopy_maps.py

    - name: Install
      shell: bash -l {0}
      run: python -m pip install --no-deps .
