name: 'Install Using Conda'
description: 'Setup environment and install using a Conda-based toolchain'
inputs:
  type:
    description: 'Whether test or doc build'
    required: true
  python-version:
    description: 'What version of Python to use'
    required: true
runs:
  using: composite
  steps:
    - name: Setup conda caching
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key: conda-${{ inputs.type }}-${{ runner.os }}-${{ inputs.python-version}}-${{ hashFiles('ci/*') }}
        restore-keys: |
          conda-${{ inputs.type }}-${{ runner.os }}-${{ inputs.python-version}}
          conda-${{ inputs.type }}-${{ runner.os }}
          conda-${{ inputs.type }}-

    - name: Set up Python ${{ inputs.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
        miniforge-variant: mambaforge
        python-version: ${{ inputs.python-version }}
        channel-priority: strict
        channels: conda-forge/label/testing,conda-forge
        show-channel-urls: true
        # Needed for caching
        use-only-tar-bz2: true

    - name: Install dependencies
      shell: bash -l {0}
      run: mamba install --quiet --yes --file ci/${{ inputs.type }}_requirements.txt --file ci/extra_requirements.txt --file ci/requirements.txt

    - name: Download Cartopy Maps
      shell: bash -l {0}
      run: ci/download_cartopy_maps.py

    - name: Install
      shell: bash -l {0}
      # For some reason on Windows 3.7 building the wheel fails to properly include our extra
      # stuff. Executing the egg_info beforehand for some reason fixes it. No idea why. We're
      # deep in territory where googling for answers helps not at all.
      run: |
        python setup.py egg_info
        python -m pip install --no-deps .
