# Copyright (c) 2016,2017,2019 MetPy Developers.
# Distributed under the terms of the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause
"""Collection of pre-defined areas for plotting with associated projections."""

import pandas as pd

from .cartopy_utils import import_cartopy
from ..package_tools import Exporter

ccrs = import_cartopy()
exporter = Exporter(globals())

area_data = [{'area': 'tropatl', 'name': 'TROPICAL ATLANTIC',
              'bounds': (-115.0, 10.0, 0.0, 40.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'subtrop', 'name': 'SUBTROPICAL ATL',
              'bounds': (-90.0, -20.0, 20.0, 60.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'troppac', 'name': 'TROPICAL PACIFIC',
              'bounds': (-165.0, -80.0, -25.0, 45.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'gulf', 'name': 'GULF OF MEXICO',
              'bounds': (-105.0, -70.0, 10.0, 40.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'carib', 'name': 'CARIBBEAN SEA',
              'bounds': (-100.0, -50.0, 0.0, 40.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'sthepac', 'name': 'SOUTH E PACIFIC',
              'bounds': (-170.0, -70.0, -60.0, 0.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'natlmed', 'name': 'N ATL/MEDITER',
              'bounds': (-30.0, 70.0, 0.0, 65.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'atlhur', 'name': 'ATLANTIC HURR',
              'bounds': (-96.0, -6.0, 4.0, 3.0),
              'proj': ccrs.NorthPolarStereo(central_longitude=-90)},
             {'area': 'nam', 'name': 'N AMERICA',
              'bounds': (-144, -50, 12, 75),
              'proj': ccrs.NorthPolarStereo(central_longitude=-105)},
             {'area': 'sam', 'name': 'S AMERICA',
              'bounds': (-120.0, -20.0, -60.0, 20.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'samps', 'name': 'S AMERICA (PS)',
              'bounds': (-100.0, -34.0, -58.0, 15.0),
              'proj': ccrs.RotatedPole(pole_latitude=90, pole_longitude=0,
                                       central_rotated_longitude=-70)},
             {'area': 'eur', 'name': 'EUROPE',
              'bounds': (-16.0, 80.0, 24.0, 52.0),
              'proj': ccrs.NorthPolarStereo(central_longitude=15)},
             {'area': 'natl', 'name': 'N ATLANTIC',
              'bounds': (-110.0, 20.1, 15.0, 70.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'watl', 'name': 'W ATLANTIC',
              'bounds': (-84.0, -38.0, 25.0, 46.0),
              'proj': ccrs.NorthPolarStereo(central_longitude=-67)},
             {'area': 'tatl', 'name': 'TROPICAL ATLANTIC',
              'bounds': (-90.0, -15.0, -10.0, 35.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'npac', 'name': 'N PACIFIC',
              'bounds': (102.0, 250.0, -12.0, 60.0),
              'proj': ccrs.PlateCarree(central_longitude=-180)},
             {'area': 'spac', 'name': 'S PACIFIC',
              'bounds': (102.0, 290.0, -60.0, 20.0),
              'proj': ccrs.PlateCarree(central_longitude=-180)},
             {'area': 'tpac', 'name': 'TROPICAL PACIFIC',
              'bounds': (-165.0, -75.0, -10.0, 40.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'epac', 'name': 'E PACIFIC',
              'bounds': (-150.0, -98.0, 12.0, 60.0),
              'proj': ccrs.RotatedPole(pole_latitude=90, pole_longitude=0,
                                       central_rotated_longitude=-130)},
             {'area': 'wpac', 'name': 'W PACIFIC',
              'bounds': (130.0, 240.0, 0.0, 63.0),
              'proj': ccrs.PlateCarree(central_longitude=-180)},
             {'area': 'mpac', 'name': 'MARINE PACIFIC',
              'bounds': (128.0, 252.0, 15.0, 71.95),
              'proj': ccrs.PlateCarree(central_longitude=-180)},
             {'area': 'americas', 'name': 'ICAO MERC AREA A',
              'bounds': (-137.4, -12.6, -54.0, 67.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'atlantic', 'name': 'ICAO MERC AREA B1',
              'bounds': (-125.0, 40.0, -45.5, 62.7),
              'proj': ccrs.PlateCarree()},
             {'area': 'africa', 'name': 'ICAO MERC AREA C',
              'bounds': (-35.0, 70.0, -45.0, 75.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'indocean', 'name': 'ICAO MERC AREA D',
              'bounds': (-15.0, 132.0, -27.0, 63.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'oceania', 'name': 'ICAO MERC AREA E',
              'bounds': (25.0, 180.0, -54.0, 40.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'trop_pac', 'name': 'ICAO MERC AREA F',
              'bounds': (100.0, 250, -52.7, 50.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'asia_ps', 'name': 'ICAO P.S. AREA G',
              'bounds': (34.8, 157.2, -0.8, 13.7),
              'proj': ccrs.NorthPolarStereo(central_longitude=65)},
             {'area': 'na_ps', 'name': 'ICAO P.S. AREA H',
              'bounds': (-79.1, 56.7, 1.6, 25.2),
              'proj': ccrs.NorthPolarStereo(central_longitude=-45)},
             {'area': 'npac_ps', 'name': 'ICAO P.S. AREA I',
              'bounds': (166.24, -60.62, -6.74, 33.32),
              'proj': ccrs.NorthPolarStereo(central_longitude=-155)},
             {'area': 'antarctica', 'name': 'ICAO P.S. AREA J',
              'bounds': (106.8, -101.1, -27.6, 0.8),
              'proj': ccrs.SouthPolarStereo(central_longitude=-142)},
             {'area': 'europe', 'name': 'ICAO P.S. AREA EU',
              'bounds': (-21.6, 68.4, 21.4, 58.7),
              'proj': ccrs.Stereographic(central_latitude=90,
                                         central_longitude=11)},
             {'area': 'middle_east', 'name': 'ICAO MERC AREA ME',
              'bounds': (17.0, 70.0, 10.0, 44.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'india', 'name': 'ICAO MERC AREA AS',
              'bounds': (53.0, 108.0, 0.0, 36.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'us', 'name': 'UNITED STATES',
              'bounds': (-119., -56., 19., 47.),
              'proj': ccrs.NorthPolarStereo(central_longitude=-100)},
             {'area': 'awips', 'name': 'AWIPS US',
              'bounds': (-127.0, -59.0, 20.0, 50.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-100)},
             {'area': 'uslcc', 'name': 'UNITED STATES LCC',
              'bounds': (-124.0, -62.0, 20.0, 51.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-100)},
             {'area': 'whlf', 'name': 'WESTERN HALF',
              'bounds': (-123.8, -85.9, 22.9, 50.2),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-105)},
             {'area': 'chlf', 'name': 'CENTRAL HALF',
              'bounds': (-111.0, -79.0, 27.5, 50.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-100)},
             {'area': 'centus', 'name': 'CENTRAL US',
              'bounds': (-105.4, -77.0, 24.7, 47.6),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-100)},
             {'area': 'ehlf', 'name': 'EASTERN HALF',
              'bounds': (-96.2, -62.7, 22.0, 49.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-90)},
             {'area': 'mehlf', 'name': 'EASTERN HALF',
              'bounds': (-89.9, -66.6, 23.8, 49.1),
              'proj': ccrs.PlateCarree()},
             {'area': 'bosfa', 'name': 'BOSTON FA AREA',
              'bounds': (-87.5, -63.5, 34.5, 50.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-75)},
             {'area': 'miafa', 'name': 'MIAMI FA AREA',
              'bounds': (-88.0, -72.0, 23.0, 39.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-80)},
             {'area': 'chifa', 'name': 'CHICAGO FA AREA',
              'bounds': (-108.0, -75.0, 34.0, 50.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-93)},
             {'area': 'dfwfa', 'name': 'DALLAS FA AREA',
              'bounds': (-106.5, -80.5, 22.0, 40.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-99)},
             {'area': 'slcfa', 'name': 'SALT LAKE FA AREA',
              'bounds': (-126.0, -98.0, 29.5, 50.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-109)},
             {'area': 'sfofa', 'name': 'SAN FRAN FA AREA',
              'bounds': (-129.0, -111.0, 30.0, 50.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-118)},
             {'area': 'west', 'name': 'WESTERN US',
              'bounds': (-125.0, -90.0, 25.0, 55.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-105)},
             {'area': 'cent', 'name': 'CENTRAL US',
              'bounds': (-107.4, -75.3, 24.3, 49.7),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-96)},
             {'area': 'east', 'name': 'EASTERN US',
              'bounds': (-100.55, -65.42, 24.57, 47.2),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-90)},
             {'area': 'nwus', 'name': 'NW SECTOR',
              'bounds': (-126.0, -102.0, 38.25, 50.25),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-114)},
             {'area': 'swus', 'name': 'SW SECTOR',
              'bounds': (-126.0, -100.0, 28.25, 40.25),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-110)},
             {'area': 'ncus', 'name': 'NC SECTOR',
              'bounds': (-108.0, -84.0, 38.25, 50.25),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-98)},
             {'area': 'scus', 'name': 'SC SECTOR',
              'bounds': (-108.9, -84.0, 24.0, 40.25),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-100)},
             {'area': 'neus', 'name': 'NE SECTOR',
              'bounds': (-89.0, -64.0, 37.25, 47.25),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-78)},
             {'area': 'seus', 'name': 'SE SECTOR',
              'bounds': (-90.0, -66.0, 28.25, 40.25),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-87)},
             {'area': 'ak', 'name': 'ALASKA HPC QPF',
              'bounds': (-180.0, -106.0, 42.0, 73.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-143)},
             {'area': 'al', 'name': 'ALABAMA',
              'bounds': (-95.0, -79.0, 27.0, 38.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-87)},
             {'area': 'ar', 'name': 'ARKANSAS',
              'bounds': (-100.75, -84.75, 29.5, 40.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-93)},
             {'area': 'ca', 'name': 'CALIFORNIA',
              'bounds': (-127.75, -111.75, 31.5, 42.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-120)},
             {'area': 'co', 'name': 'COLORADO',
              'bounds': (-114.0, -98.0, 33.5, 44.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-106)},
             {'area': 'ct', 'name': 'CONNECTICUT',
              'bounds': (-81.25, -65.25, 36.0, 47.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-73)},
             {'area': 'dc', 'name': 'WASHINGTON DC',
              'bounds': (-85.0, -69.0, 33.35, 44.35),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-77)},
             {'area': 'de', 'name': 'DELAWARE',
              'bounds': (-83.75, -67.75, 33.25, 44.25),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-76)},
             {'area': 'fl', 'name': 'FLORIDA',
              'bounds': (-90.0, -74.0, 23.0, 34.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-82)},
             {'area': 'ga', 'name': 'GEORGIA',
              'bounds': (-92.0, -76.0, 27.5, 38.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-84)},
             {'area': 'hi', 'name': 'HAWAII',
              'bounds': (-161.5, -152.5, 17.0, 23.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'ia', 'name': 'IOWA',
              'bounds': (-102.0, -86.0, 36.5, 47.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-94)},
             {'area': 'id', 'name': 'IDAHO',
              'bounds': (-123.0, -107.0, 39.25, 50.25),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-115)},
             {'area': 'il', 'name': 'ILLINOIS',
              'bounds': (-97.75, -81.75, 34.5, 45.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-90)},
             {'area': 'in', 'name': 'INDIANA',
              'bounds': (-94.5, -78.5, 34.5, 45.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-87)},
             {'area': 'ks', 'name': 'KANSAS',
              'bounds': (-106.5, -90.5, 33.25, 44.25),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-99)},
             {'area': 'ky', 'name': 'KENTUCKY',
              'bounds': (-93.0, -77.0, 31.75, 42.75),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-85)},
             {'area': 'la', 'name': 'LOUISIANA',
              'bounds': (-100.75, -84.75, 25.75, 36.75),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-93)},
             {'area': 'ma', 'name': 'MASSACHUSETTS',
              'bounds': (-80.25, -64.25, 36.75, 47.75),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-72)},
             {'area': 'md', 'name': 'MARYLAND',
              'bounds': (-85.25, -69.25, 33.75, 44.75),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-77)},
             {'area': 'me', 'name': 'MAINE',
              'bounds': (-77.75, -61.75, 39.5, 50.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-70)},
             {'area': 'mi', 'name': 'MICHIGAN',
              'bounds': (-93.0, -77.0, 37.75, 48.75),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-85)},
             {'area': 'mn', 'name': 'MINNESOTA',
              'bounds': (-102.0, -86.0, 40.5, 51.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-94)},
             {'area': 'mo', 'name': 'MISSOURI',
              'bounds': (-101.0, -85.0, 33.0, 44.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-93)},
             {'area': 'ms', 'name': 'MISSISSIPPI',
              'bounds': (-98.0, -82.0, 27.0, 38.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-90)},
             {'area': 'mt', 'name': 'MONTANA',
              'bounds': (-117.0, -101.0, 41.5, 52.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-109)},
             {'area': 'nc', 'name': 'NORTH CAROLINA',
              'bounds': (-87.25, -71.25, 30.0, 41.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-79)},
             {'area': 'nd', 'name': 'NORTH DAKOTA',
              'bounds': (-107.5, -91.5, 42.25, 53.25),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-100)},
             {'area': 'ne', 'name': 'NEBRASKA',
              'bounds': (-107.5, -91.5, 36.25, 47.25),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-100)},
             {'area': 'nh', 'name': 'NEW HAMPSHIRE',
              'bounds': (-79.5, -63.5, 38.25, 49.25),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-72)},
             {'area': 'nj', 'name': 'NEW JERSEY',
              'bounds': (-82.5, -66.5, 34.75, 45.75),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-75)},
             {'area': 'nm', 'name': 'NEW MEXICO',
              'bounds': (-114.25, -98.25, 29.0, 40.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-106)},
             {'area': 'nv', 'name': 'NEVADA',
              'bounds': (-125.0, -109.0, 34.0, 45.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-117)},
             {'area': 'ny', 'name': 'NEW YORK',
              'bounds': (-84.0, -68.0, 37.25, 48.25),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-76)},
             {'area': 'oh', 'name': 'OHIO',
              'bounds': (-91.0, -75.0, 34.5, 45.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-83)},
             {'area': 'ok', 'name': 'OKLAHOMA',
              'bounds': (-105.25, -89.25, 30.25, 41.25),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-97)},
             {'area': 'or', 'name': 'OREGON',
              'bounds': (-128.0, -112.0, 38.75, 49.75),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-120)},
             {'area': 'pa', 'name': 'PENNSYLVANIA',
              'bounds': (-86.0, -70.0, 35.5, 46.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-78)},
             {'area': 'ri', 'name': 'RHODE ISLAND',
              'bounds': (-79.75, -63.75, 36.0, 47.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-72)},
             {'area': 'sc', 'name': 'SOUTH CAROLINA',
              'bounds': (-89.0, -73.0, 28.5, 39.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-81)},
             {'area': 'sd', 'name': 'SOUTH DAKOTA',
              'bounds': (-107.5, -91.5, 39.0, 50.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-100)},
             {'area': 'tn', 'name': 'TENNESSEE',
              'bounds': (-95.0, -79.0, 30.0, 41.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-87)},
             {'area': 'tx', 'name': 'TEXAS',
              'bounds': (-107.0, -91.0, 25.4, 36.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-99)},
             {'area': 'ut', 'name': 'UTAH',
              'bounds': (-119.0, -103.0, 34.0, 45.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-111)},
             {'area': 'va', 'name': 'VIRGINIA',
              'bounds': (-86.5, -70.5, 32.25, 43.25),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-79)},
             {'area': 'vt', 'name': 'VERMONT',
              'bounds': (-80.75, -64.75, 38.25, 49.25),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-73)},
             {'area': 'wi', 'name': 'WISCONSIN',
              'bounds': (-98.0, -82.0, 38.5, 49.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-90)},
             {'area': 'wv', 'name': 'WEST VIRGINIA',
              'bounds': (-89.0, -73.0, 33.0, 44.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-81)},
             {'area': 'wy', 'name': 'WYOMING',
              'bounds': (-116.0, -100.0, 37.75, 48.75),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-108)},
             {'area': 'az', 'name': 'ARIZONA',
              'bounds': (-119.0, -103.0, 29.0, 40.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-111)},
             {'area': 'wa', 'name': 'WASHINGTON',
              'bounds': (-128.0, -112.0, 41.75, 52.75),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-120)},
             {'area': 'cn', 'name': 'CANADA',
              'bounds': (-120.4, -14.0, 37.9, 58.6),
              'proj': ccrs.NorthPolarStereo(central_longitude=-90)},
             {'area': 'cnlcc', 'name': 'CANADA LCC',
              'bounds': (-127, -54.0, 40, 70),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-100)},
             {'area': 'ab', 'name': 'ALBERTA',
              'bounds': (-119.6, -108.2, 48.6, 60.4),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-114)},
             {'area': 'bc', 'name': 'BRITISH COLUMBIA',
              'bounds': (-134.5, -109.0, 47.2, 60.7),
              'proj': ccrs.NorthPolarStereo(central_longitude=-122)},
             {'area': 'mb', 'name': 'MANITOBA',
              'bounds': (-102.4, -86.1, 48.3, 60.2),
              'proj': ccrs.NorthPolarStereo(central_longitude=-95)},
             {'area': 'nb', 'name': 'NEW BRUNSWICK',
              'bounds': (-75.7, -57.6, 42.7, 49.6),
              'proj': ccrs.NorthPolarStereo(central_longitude=-67)},
             {'area': 'nf', 'name': 'NEWFOUNDLAND',
              'bounds': (-68.0, -47.0, 45.0, 62.0),
              'proj': ccrs.NorthPolarStereo(central_longitude=-58)},
             {'area': 'ns', 'name': 'NOVA SCOTIA',
              'bounds': (-67.0, -59.0, 43.0, 47.5),
              'proj': ccrs.NorthPolarStereo(central_longitude=-63)},
             {'area': 'nt', 'name': 'NW TERRITORIES',
              'bounds': (-132.0, -100.0, 59.0, 70.5),
             'proj': ccrs.NorthPolarStereo(central_longitude=-112)},
             {'area': 'nu', 'name': 'NUNAVUT',
              'bounds': (-115.0, -65.0, 59.0, 80),
              'proj': ccrs.NorthPolarStereo(central_longitude=-95)},
             {'area': 'on', 'name': 'ONTARIO',
              'bounds': (-94.5, -68.2, 41.9, 55.0),
              'proj': ccrs.NorthPolarStereo(central_longitude=-90)},
             {'area': 'pe', 'name': 'PRINCE EDWARD IS',
              'bounds': (-64.6, -61.7, 45.8, 47.1),
              'proj': ccrs.NorthPolarStereo(central_longitude=-63)},
             {'area': 'qb', 'name': 'QUEBEC',
              'bounds': (-80.0, -49.2, 44.1, 60.9),
              'proj': ccrs.NorthPolarStereo(central_longitude=-74)},
             {'area': 'sa', 'name': 'SASKATCHEWAN',
              'bounds': (-111.2, -97.8, 48.5, 60.3),
              'proj': ccrs.NorthPolarStereo(central_longitude=-105)},
             {'area': 'yt', 'name': 'YUKON TERRITORY',
              'bounds': (-142.0, -117.0, 59.0, 70.5),
              'proj': ccrs.NorthPolarStereo(central_longitude=-130)},
             {'area': 'ag', 'name': 'ARGENTINA',
              'bounds': (-80.0, -53.0, -56.0, -20.0),
              'proj': ccrs.SouthPolarStereo(central_longitude=-67)},
             {'area': 'ah', 'name': 'AFGHANISTAN',
              'bounds': (60.0, 77.0, 27.0, 40.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=69)},
             {'area': 'afrca', 'name': 'AFRICA',
              'bounds': (-25.0, 59.4, -36.0, 41.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'ai', 'name': 'ASCENSION ISLAND',
              'bounds': (-14.3, -14.1, -8.0, -7.8),
              'proj': ccrs.PlateCarree()},
             {'area': 'alba', 'name': 'ALBANIA',
              'bounds': (18.0, 23.0, 39.0, 43.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=21)},
             {'area': 'alge', 'name': 'ALGERIA',
              'bounds': (-9.0, 12.0, 15.0, 38.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'an', 'name': 'ANGOLA',
              'bounds': (10.0, 25.0, -20.0, -5.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'antl', 'name': 'LESSER ANTILLES',
              'bounds': (-70.0, -58.0, 11.0, 19.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'antg', 'name': 'GREATER ANTILLES',
              'bounds': (-86.0, -65.0, 17.0, 25.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'atg', 'name': 'ANTIGUA & BARBUDA',
              'bounds': (-62.0, -61.6, 16.9, 17.75),
              'proj': ccrs.PlateCarree()},
             {'area': 'au', 'name': 'AUSTRALIA',
              'bounds': (110.0, 160.0, -40.0, -6.5),
              'proj': ccrs.SouthPolarStereo(central_longitude=140)},
             {'area': 'azor', 'name': 'AZORES',
              'bounds': (-27.6, -23.0, 36.0, 41.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-25)},
             {'area': 'ba', 'name': 'BAHAMAS',
              'bounds': (-80.5, -72.5, 22.5, 28.5),
              'proj': ccrs.PlateCarree()},
             {'area': 'be', 'name': 'BERMUDA',
              'bounds': (-64.9, -64.5, 32.2, 32.6),
              'proj': ccrs.PlateCarree()},
             {'area': 'bel', 'name': 'BELGIUM',
              'bounds': (2.5, 6.5, 49.4, 51.6),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=5)},
             {'area': 'bf', 'name': 'BRUNEI',
              'bounds': (113.0, 116.0, 4.0, 5.5),
              'proj': ccrs.PlateCarree()},
             {'area': 'bfa', 'name': 'BURKINA FASO',
              'bounds': (-6.0, 3.0, 9.0, 15.1),
              'proj': ccrs.PlateCarree()},
             {'area': 'bh', 'name': 'BELIZE',
              'bounds': (-89.3, -88.1, 15.7, 18.5),
              'proj': ccrs.PlateCarree()},
             {'area': 'bi', 'name': 'BURUNDI',
              'bounds': (29.0, 30.9, -4.6, -2.2),
              'proj': ccrs.PlateCarree()},
             {'area': 'bj', 'name': 'BENIN',
              'bounds': (0.0, 5.0, 6.0, 12.6),
              'proj': ccrs.PlateCarree()},
             {'area': 'bn', 'name': 'BAHRAIN',
              'bounds': (50.0, 51.0, 25.5, 27.1),
              'proj': ccrs.PlateCarree()},
             {'area': 'bo', 'name': 'BOLIVIA',
              'bounds': (-72.0, -50.0, -24.0, -8.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'bots', 'name': 'BOTSWANA',
              'bounds': (19.0, 29.6, -27.0, -17.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'br', 'name': 'BARBADOS',
              'bounds': (-62.5, -56.5, 12.45, 13.85),
              'proj': ccrs.PlateCarree()},
             {'area': 'bt', 'name': 'BRITISH INDIAN OC',
              'bounds': (71.25, 72.6, -7.5, -5.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'bu', 'name': 'BULGARIA',
              'bounds': (22.0, 30.0, 40.0, 45.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=26)},
             {'area': 'bv', 'name': 'BOUVET ISLANDS',
              'bounds': (3.0, 4.0, -55.0, -54.0),
              'proj': ccrs.SouthPolarStereo(central_longitude=4)},
             {'area': 'bw', 'name': 'BANGLADESH',
              'bounds': (87.0, 93.0, 20.8, 27.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'by', 'name': 'BYELORUSSIA',
              'bounds': (19.0, 33.0, 51.0, 60.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=26)},
             {'area': 'bz', 'name': 'BRAZIL',
              'bounds': (-75.0, -30.0, -35.0, 5.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'cais', 'name': 'CANTON ISLAND',
              'bounds': (-172.0, -171.0, -3.0, -2.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'nwcar', 'name': 'NWX CARIBBEAN',
              'bounds': (-120.0, -50.0, -15.0, 35.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'cari', 'name': 'CARIBBEAN',
              'bounds': (-103.0, -53.0, 3.0, 36.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'cb', 'name': 'CHAD',
              'bounds': (13.0, 25.0, 7.0, 24.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'ce', 'name': 'CENTRAL AFRICA',
              'bounds': (14.0, 29.0, 2.0, 11.5),
              'proj': ccrs.PlateCarree()},
             {'area': 'cg', 'name': 'CONGO',
              'bounds': (10.0, 20.0, -6.0, 5.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'ch', 'name': 'CHILE',
              'bounds': (-80.0, -66.0, -56.0, -15.0),
              'proj': ccrs.SouthPolarStereo(central_longitude=-73)},
             {'area': 'ci', 'name': 'CHINA',
              'bounds': (85.0, 145.0, 14.0, 48.5),
              'proj': ccrs.NorthPolarStereo(central_longitude=110)},
             {'area': 'cm', 'name': 'CAMEROON',
              'bounds': (7.5, 17.1, 1.0, 14.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'colm', 'name': 'COLUMBIA',
              'bounds': (-81.0, -65.0, -5.0, 14.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'cr', 'name': 'CANARY ISLANDS',
              'bounds': (-19.0, -13.0, 27.0, 30.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'cs', 'name': 'COSTA RICA',
              'bounds': (-86.5, -81.5, 8.2, 11.6),
              'proj': ccrs.PlateCarree()},
             {'area': 'cu', 'name': 'CUBA',
              'bounds': (-85.0, -74.0, 19.0, 24.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'cv', 'name': 'CAPE VERDE ISLAND',
              'bounds': (-26.0, -22.0, 14.0, 18.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'cy', 'name': 'CYPRUS',
              'bounds': (32.0, 35.0, 34.0, 36.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=34)},
             {'area': 'cz', 'name': 'CZECH REPUBLIC',
              'bounds': (8.9, 22.9, 47.4, 52.4),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=16)},
             {'area': 'dj', 'name': 'DJIBOUTI',
              'bounds': (41.5, 44.1, 10.5, 13.1),
              'proj': ccrs.PlateCarree()},
             {'area': 'dl', 'name': 'GERMANY',
              'bounds': (4.8, 16.8, 47.0, 55.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=11)},
             {'area': 'dn', 'name': 'DENMARK',
              'bounds': (8.0, 11.0, 54.0, 58.6),
              'proj': ccrs.NorthPolarStereo(central_longitude=10)},
             {'area': 'do', 'name': 'DOMINICA',
              'bounds': (-61.6, -61.2, 15.2, 15.8),
              'proj': ccrs.PlateCarree()},
             {'area': 'dr', 'name': 'DOMINICAN REPUBLIC',
              'bounds': (-72.2, -68.0, 17.5, 20.2),
              'proj': ccrs.PlateCarree()},
             {'area': 'eg', 'name': 'EGYPT',
              'bounds': (24.0, 37.0, 21.0, 33.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'eq', 'name': 'ECUADOR',
              'bounds': (-85.0, -74.0, -7.0, 3.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'er', 'name': 'UAE',
              'bounds': (50.0, 57.0, 22.0, 26.6),
              'proj': ccrs.PlateCarree()},
             {'area': 'es', 'name': 'EL SALVADOR',
              'bounds': (-90.3, -87.5, 13.0, 14.6),
             'proj': ccrs.PlateCarree()},
             {'area': 'et', 'name': 'ETHIOPIA',
              'bounds': (33.0, 49.0, 2.0, 19.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'fa', 'name': 'FAEROES',
              'bounds': (-8.0, -6.0, 61.0, 63.0),
              'proj': ccrs.NorthPolarStereo(central_longitude=-7)},
             {'area': 'fg', 'name': 'FRENCH GUIANA',
              'bounds': (-55.0, -49.0, 1.0, 7.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'fi', 'name': 'FINLAND',
              'bounds': (20.9, 35.1, 59.0, 70.6),
              'proj': ccrs.NorthPolarStereo(central_longitude=28)},
             {'area': 'fj', 'name': 'FIJI ISLANDS',
              'bounds': (176.0, 181.0, 16.0, 19.0),
              'proj': ccrs.PlateCarree(central_longitude=-180)},
             {'area': 'fk', 'name': 'FALKLAND ISLANDS',
              'bounds': (-61.3, -57.5, -53.0, -51.0),
              'proj': ccrs.SouthPolarStereo(central_longitude=-57)},
             {'area': 'fn', 'name': 'NIGER',
              'bounds': (0.0, 17.0, 11.0, 24.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'fr', 'name': 'FRANCE',
              'bounds': (-5.0, 11.0, 41.0, 51.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=3)},
             {'area': 'gb', 'name': 'GAMBIA',
              'bounds': (-17.1, -13.5, 13.0, 14.6),
              'proj': ccrs.PlateCarree()},
             {'area': 'gc', 'name': 'CAYMAN ISLANDS',
              'bounds': (-82.8, -77.6, 17.9, 21.1),
              'proj': ccrs.PlateCarree()},
             {'area': 'gh', 'name': 'GHANA',
              'bounds': (-4.5, 1.5, 4.0, 12.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'gi', 'name': 'GIBRALTAR',
              'bounds': (-8.0, -4.0, 35.0, 38.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-6)},
             {'area': 'gl', 'name': 'GREENLAND',
              'bounds': (-60, -20, 58.3, 85),
              'proj': ccrs.NorthPolarStereo(central_longitude=-45)},
             {'area': 'glp', 'name': 'GUADALOUPE',
              'bounds': (-64.2, -59.8, 14.8, 19.2),
              'proj': ccrs.PlateCarree()},
             {'area': 'gm', 'name': 'GUAM',
              'bounds': (144.5, 145.1, 13.0, 14.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'gn', 'name': 'GUINEA',
              'bounds': (2.0, 16.0, 3.5, 15.5),
              'proj': ccrs.PlateCarree()},
             {'area': 'go', 'name': 'GABON',
              'bounds': (8.0, 14.5, -4.6, 3.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'gr', 'name': 'GREECE',
              'bounds': (20.0, 27.6, 34.0, 42.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=24)},
             {'area': 'gu', 'name': 'GUATEMALA',
              'bounds': (-95.6, -85.0, 10.5, 21.1),
              'proj': ccrs.PlateCarree()},
             {'area': 'gw', 'name': 'GUINEA-BISSAU',
              'bounds': (-17.5, -13.5, 10.8, 12.8),
              'proj': ccrs.PlateCarree()},
             {'area': 'gy', 'name': 'GUYANA',
              'bounds': (-62.0, -55.0, 0.0, 10.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'ha', 'name': 'HAITI',
              'bounds': (-75.0, -71.0, 18.0, 20.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'he', 'name': 'ST HELENA',
              'bounds': (-6.1, -5.5, -16.3, -15.5),
              'proj': ccrs.PlateCarree()},
             {'area': 'hk', 'name': 'HONG KONG',
              'bounds': (113.5, 114.7, 22.0, 23.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'ho', 'name': 'HONDURAS',
              'bounds': (-90.0, -83.0, 13.0, 16.6),
              'proj': ccrs.PlateCarree()},
             {'area': 'hu', 'name': 'HUNGARY',
              'bounds': (16.0, 23.0, 45.5, 49.1),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=20)},
             {'area': 'ic', 'name': 'COMOROS',
              'bounds': (43.0, 45.0, -13.2, -11.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'icel', 'name': 'ICELAND',
              'bounds': (-24.1, -11.5, 63.0, 67.5),
              'proj': ccrs.NorthPolarStereo(central_longitude=-18)},
             {'area': 'ie', 'name': 'IRELAND',
              'bounds': (-11.1, -4.5, 50.0, 55.6),
              'proj': ccrs.NorthPolarStereo(central_longitude=-8)},
             {'area': 'inda', 'name': 'INDIA',
              'bounds': (67.0, 92.0, 4.2, 36.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'indo', 'name': 'INDONESIA',
              'bounds': (95.0, 141.0, -8.0, 6.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'iq', 'name': 'IRAQ',
              'bounds': (38.0, 50.0, 29.0, 38.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'ir', 'name': 'IRAN',
              'bounds': (44.0, 65.0, 25.0, 40.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'is', 'name': 'ISRAEL',
              'bounds': (34.0, 37.0, 29.0, 34.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'iv', 'name': 'IVORY COAST',
              'bounds': (-9.0, -2.0, 4.0, 11.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'iw', 'name': 'WEST BANK',
              'bounds': (34.8, 35.6, 31.2, 32.6),
              'proj': ccrs.PlateCarree()},
             {'area': 'iy', 'name': 'ITALY',
              'bounds': (6.6, 20.6, 35.6, 47.2),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=14)},
             {'area': 'jd', 'name': 'JORDAN',
              'bounds': (34.0, 39.6, 29.0, 33.6),
              'proj': ccrs.PlateCarree()},
             {'area': 'jm', 'name': 'JAMAICA',
              'bounds': (-80.0, -76.0, 16.0, 19.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'jp', 'name': 'JAPAN',
              'bounds': (123.0, 155.0, 24.0, 47.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=139)},
             {'area': 'ka', 'name': 'CAROLINE ISLANDS',
              'bounds': (131.0, 155.0, 1.0, 9.6),
              'proj': ccrs.PlateCarree()},
             {'area': 'kash', 'name': 'JAMMU & KASHMIR',
              'bounds': (74.0, 78.0, 32.0, 35.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'kb', 'name': 'KIRIBATI',
              'bounds': (172.0, 177.0, -3.0, 3.2),
              'proj': ccrs.PlateCarree()},
             {'area': 'khm', 'name': 'CAMBODIA',
              'bounds': (102.0, 108.0, 10.0, 15.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'ki', 'name': 'CHRISTMAS ISLAND',
              'bounds': (105.2, 106.2, -11.0, -10.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'kn', 'name': 'KENYA',
              'bounds': (32.5, 42.1, -6.0, 6.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'kna', 'name': 'ST KITTS & NEVIS',
              'bounds': (-62.9, -62.4, 17.0, 17.5),
              'proj': ccrs.PlateCarree()},
             {'area': 'ko', 'name': 'KOREA',
              'bounds': (124.0, 131.5, 33.0, 43.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=128)},
             {'area': 'ku', 'name': 'COOK ISLANDS',
              'bounds': (-168.0, -155.0, -24.1, -6.1),
              'proj': ccrs.PlateCarree()},
             {'area': 'kw', 'name': 'KUWAIT',
              'bounds': (46.5, 48.5, 28.5, 30.5),
              'proj': ccrs.PlateCarree()},
             {'area': 'laos', 'name': 'LAOS',
              'bounds': (100.0, 108.0, 13.5, 23.1),
              'proj': ccrs.PlateCarree()},
             {'area': 'lb', 'name': 'LEBANON',
              'bounds': (34.5, 37.1, 33.0, 35.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'lc', 'name': 'ST LUCIA',
              'bounds': (60.9, 61.3, 13.25, 14.45),
              'proj': ccrs.PlateCarree()},
             {'area': 'li', 'name': 'LIBERIA',
              'bounds': (-12.0, -7.0, 4.0, 9.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'ln', 'name': 'LINE ISLANDS',
              'bounds': (-162.1, -154.9, -4.2, 6.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'ls', 'name': 'LESOTHO',
              'bounds': (27.0, 29.6, -30.6, -28.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'lt', 'name': 'LIECHTENSTEIN',
              'bounds': (9.3, 9.9, 47.0, 47.6),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=10)},
             {'area': 'lux', 'name': 'LUXEMBOURG',
              'bounds': (5.6, 6.6, 49.35, 50.25),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=6)},
             {'area': 'ly', 'name': 'LIBYA',
              'bounds': (8.0, 26.0, 19.0, 35.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'maar', 'name': 'ST MAARTEN',
              'bounds': (-63.9, -62.3, 17.0, 18.6),
              'proj': ccrs.PlateCarree()},
             {'area': 'made', 'name': 'MADEIRA',
              'bounds': (-17.3, -16.5, 32.6, 33.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'mala', 'name': 'MALAYSIA',
              'bounds': (100.0, 119.6, 1.0, 8.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'mali', 'name': 'MALI',
              'bounds': (-12.5, 6.0, 8.5, 25.5),
              'proj': ccrs.PlateCarree()},
             {'area': 'maur', 'name': 'MAURITIUS',
              'bounds': (57.2, 57.8, -20.7, -19.9),
              'proj': ccrs.PlateCarree()},
             {'area': 'maut', 'name': 'MAURITANIA',
              'bounds': (-17.1, -4.5, 14.5, 28.1),
              'proj': ccrs.PlateCarree()},
             {'area': 'mc', 'name': 'MOROCCO',
              'bounds': (-13.0, -1.0, 25.0, 36.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'mg', 'name': 'MADAGASCAR',
              'bounds': (43.0, 50.6, -25.6, -12.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'mh', 'name': 'MARSHALL ISLANDS',
              'bounds': (160.0, 172.0, 4.5, 12.1),
              'proj': ccrs.PlateCarree()},
             {'area': 'ml', 'name': 'MALTA',
              'bounds': (14.3, 14.7, 35.8, 36.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'mmr', 'name': 'MYANMAR',
              'bounds': (92.0, 102.0, 7.5, 28.5),
              'proj': ccrs.PlateCarree()},
             {'area': 'mong', 'name': 'MONGOLIA',
              'bounds': (87.5, 123.1, 38.5, 52.6),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=105)},
             {'area': 'mr', 'name': 'MARTINIQUE',
              'bounds': (-61.2, -60.8, 14.3, 15.1),
              'proj': ccrs.PlateCarree()},
             {'area': 'mu', 'name': 'MACAO',
              'bounds': (113.0, 114.0, 22.0, 23.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'mv', 'name': 'MALDIVE ISLANDS',
              'bounds': (70.1, 76.1, -6.0, 10.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'mw', 'name': 'MALAWI',
              'bounds': (32.5, 36.1, -17.0, -9.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'mx', 'name': 'MEXICO',
              'bounds': (-119.0, -83.0, 13.0, 34.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'my', 'name': 'MARIANNA ISLANDS',
              'bounds': (142.5, 148.5, 9.0, 25.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'mz', 'name': 'MOZAMBIQUE',
              'bounds': (29.0, 41.0, -26.5, -9.5),
              'proj': ccrs.PlateCarree()},
             {'area': 'nama', 'name': 'NAMIBIA',
              'bounds': (11.0, 25.0, -29.5, -16.5),
              'proj': ccrs.PlateCarree()},
             {'area': 'ncal', 'name': 'NEW CALEDONIA',
              'bounds': (158.0, 172.0, -23.0, -18.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'ng', 'name': 'NEW GUINEA',
              'bounds': (130.0, 152.0, -11.0, 0.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'ni', 'name': 'NIGERIA',
              'bounds': (2.0, 14.6, 3.0, 14.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'nk', 'name': 'NICARAGUA',
              'bounds': (-88.0, -83.0, 10.5, 15.1),
              'proj': ccrs.PlateCarree()},
             {'area': 'nl', 'name': 'NETHERLANDS',
              'bounds': (3.5, 7.5, 50.5, 54.1),
              'proj': ccrs.NorthPolarStereo(central_longitude=6)},
             {'area': 'no', 'name': 'NORWAY',
              'bounds': (3.0, 35.0, 57.0, 71.5),
              'proj': ccrs.NorthPolarStereo(central_longitude=19)},
             {'area': 'np', 'name': 'NEPAL',
              'bounds': (80.0, 89.0, 25.0, 31.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'nw', 'name': 'NAURU',
              'bounds': (166.4, 167.4, -1.0, 0.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'nz', 'name': 'NEW ZEALAND',
              'bounds': (165.0, 179.0, -48.0, -33.0),
              'proj': ccrs.SouthPolarStereo(central_longitude=172)},
             {'area': 'om', 'name': 'OMAN',
              'bounds': (52.0, 60.0, 16.0, 25.6),
              'proj': ccrs.PlateCarree()},
             {'area': 'os', 'name': 'AUSTRIA',
              'bounds': (9.0, 18.0, 46.0, 50.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=14)},
             {'area': 'pf', 'name': 'FRENCH POLYNESIA',
              'bounds': (-154.0, -134.0, -28.0, -8.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'ph', 'name': 'PHILIPPINES',
              'bounds': (116.0, 127.0, 4.0, 21.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'pi', 'name': 'PHOENIX ISLANDS',
              'bounds': (-177.5, -167.5, -9.0, 1.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'pk', 'name': 'PAKISTAN',
              'bounds': (60.0, 78.0, 23.0, 37.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'pl', 'name': 'POLAND',
              'bounds': (14.0, 25.0, 48.5, 55.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=20)},
             {'area': 'pm', 'name': 'PANAMA',
              'bounds': (-83.0, -77.0, 7.0, 10.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'po', 'name': 'PORTUGAL',
              'bounds': (-10.0, -4.0, 36.5, 42.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-7)},
             {'area': 'pr', 'name': 'PERU',
              'bounds': (-82.0, -68.0, -20.0, 5.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'pt', 'name': 'PITCAIRN ISLANDS',
              'bounds': (-130.6, -129.6, -25.56, -24.56),
              'proj': ccrs.PlateCarree()},
             {'area': 'pu', 'name': 'PUERTO RICO',
              'bounds': (-67.5, -65.5, 17.5, 18.5),
              'proj': ccrs.PlateCarree()},
             {'area': 'py', 'name': 'PARAGUAY',
              'bounds': (-65.0, -54.0, -32.0, -17.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'qg', 'name': 'EQUATORIAL GUINEA',
              'bounds': (7.0, 12.0, -2.0, 3.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'qt', 'name': 'QATAR',
              'bounds': (50.0, 52.0, 24.0, 27.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'ra', 'name': 'RUSSIA',
              'bounds': (40.0, 190.0, 35.0, 70.0),
              'proj': ccrs.LambertConformal(standard_parallels=[40, 70],
                                            central_longitude=105)},
             {'area': 're', 'name': 'REUNION',
              'bounds': (55.0, 56.0, -21.5, -20.5),
              'proj': ccrs.PlateCarree()},
             {'area': 'riro', 'name': 'RIO DE ORO',
              'bounds': (-18.0, -12.0, 17.5, 27.5),
              'proj': ccrs.PlateCarree()},
             {'area': 'ro', 'name': 'ROMANIA',
              'bounds': (19.0, 31.0, 42.5, 48.5),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=25)},
             {'area': 'rw', 'name': 'RWANDA',
              'bounds': (29.0, 31.0, -3.0, -1.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'saudi', 'name': 'SAUDI ARABIA',
              'bounds': (4.6, 92.5, -13.2, 60.3),
              'proj': ccrs.PlateCarree()},
             {'area': 'sb', 'name': 'SRI LANKA',
              'bounds': (79.0, 83.0, 5.0, 10.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'seyc', 'name': 'SEYCHELLES ISLANDS',
              'bounds': (55.0, 56.0, -5.0, -4.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'sg', 'name': 'SENEGAL',
              'bounds': (-18.0, -10.0, 12.0, 17.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'si', 'name': 'SOMALIA',
              'bounds': (39.5, 52.1, -4.5, 13.5),
              'proj': ccrs.PlateCarree()},
             {'area': 'sk', 'name': 'SARAWAK',
              'bounds': (109.5, 119.3, 1.0, 7.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'sl', 'name': 'SIERRA LEONE',
              'bounds': (-13.6, -10.2, 6.9, 10.1),
              'proj': ccrs.PlateCarree()},
             {'area': 'sm', 'name': 'SURINAME',
              'bounds': (-59.0, -53.0, 1.0, 6.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'sn', 'name': 'SWEDEN',
              'bounds': (10.0, 25.0, 55.0, 69.6),
              'proj': ccrs.NorthPolarStereo(central_longitude=18)},
             {'area': 'so', 'name': 'SOLOMON ISLANDS',
              'bounds': (156.0, 167.0, -12.0, -6.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'sp', 'name': 'SPAIN',
              'bounds': (-10.0, 6.0, 35.0, 44.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-2)},
             {'area': 'sr', 'name': 'SINGAPORE',
              'bounds': (103.0, 105.0, 1.0, 2.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'su', 'name': 'SUDAN',
              'bounds': (21.5, 38.5, 3.5, 23.5),
              'proj': ccrs.PlateCarree()},
             {'area': 'sv', 'name': 'SWAZILAND',
              'bounds': (30.5, 33.1, -27.5, -25.3),
              'proj': ccrs.PlateCarree()},
             {'area': 'sw', 'name': 'SWITZERLAND',
              'bounds': (5.9, 10.5, 45.8, 48.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=8)},
             {'area': 'sy', 'name': 'SYRIA',
              'bounds': (35.0, 42.6, 32.0, 37.6),
              'proj': ccrs.PlateCarree()},
             {'area': 'tanz', 'name': 'TANZANIA',
              'bounds': (29.0, 40.6, -13.0, 0.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'td', 'name': 'TRINIDAD & TOBAGO',
              'bounds': (-62.1, -60.5, 10.0, 11.6),
              'proj': ccrs.PlateCarree()},
             {'area': 'tg', 'name': 'TOGO',
              'bounds': (-0.5, 2.5, 5.0, 12.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'th', 'name': 'THAILAND',
              'bounds': (97.0, 106.0, 5.0, 21.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'ti', 'name': 'TURKS ISLANDS',
              'bounds': (-71.6, -70.6, 21.0, 22.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'tk', 'name': 'TOKELAU ISLANDS',
              'bounds': (-173.0, -171.0, -11.5, -7.5),
              'proj': ccrs.PlateCarree()},
             {'area': 'to', 'name': 'TONGA',
              'bounds': (-178.5, -170.5, -22.0, -15.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'tp', 'name': 'SAO TOME-PRINCIPE',
              'bounds': (6.0, 7.6, 0.0, 2.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'ts', 'name': 'TUNISIA',
              'bounds': (7.0, 13.0, 30.0, 38.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'tu', 'name': 'TURKEY',
              'bounds': (25.0, 48.0, 34.1, 42.1),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=37)},
             {'area': 'tv', 'name': 'TUVALU',
              'bounds': (176.0, 180.0, -11.0, -5.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'tw', 'name': 'TAIWAN',
              'bounds': (120.0, 122.0, 21.9, 25.3),
              'proj': ccrs.PlateCarree()},
             {'area': 'ug', 'name': 'UGANDA',
              'bounds': (29.0, 35.0, -3.5, 5.5),
              'proj': ccrs.PlateCarree()},
             {'area': 'uk', 'name': 'UNITED KINGDOM',
              'bounds': (-11.0, 5.0, 49.0, 60.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=-3)},
             {'area': 'ur', 'name': 'UKRAINE',
              'bounds': (20.0, 41.0, 45.0, 52.0),
              'proj': ccrs.NorthPolarStereo(central_longitude=20)},
             {'area': 'uy', 'name': 'URUGUAY',
              'bounds': (-60.0, -52.0, -35.5, -29.5),
              'proj': ccrs.SouthPolarStereo(central_longitude=-56)},
             {'area': 'vanu', 'name': 'VANUATU',
              'bounds': (167.0, 170.0, -21.0, -13.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'vi', 'name': 'VIRGIN ISLANDS',
              'bounds': (-65.5, -64.0, 16.6, 19.6),
              'proj': ccrs.PlateCarree()},
             {'area': 'vk', 'name': 'SLOVAKIA',
              'bounds': (13.8, 25.8, 46.75, 50.75),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=20)},
             {'area': 'vn', 'name': 'VENEZUELA',
              'bounds': (-75.0, -60.0, -2.0, 14.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'vs', 'name': 'VIETNAM',
              'bounds': (102.0, 110.0, 8.0, 24.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'wk', 'name': 'WAKE ISLAND',
              'bounds': (166.1, 167.1, 18.8, 19.8),
              'proj': ccrs.PlateCarree()},
             {'area': 'ye', 'name': 'YEMEN',
              'bounds': (42.5, 54.1, 12.5, 19.1),
              'proj': ccrs.PlateCarree()},
             {'area': 'yg', 'name': 'YUGOSLAVIA',
              'bounds': (13.5, 24.6, 40.0, 47.0),
              'proj': ccrs.LambertConformal(standard_parallels=[30, 60],
                                            central_longitude=19)},
             {'area': 'za', 'name': 'SOUTH AFRICA',
              'bounds': (16.0, 34.0, -36.0, -22.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'zb', 'name': 'ZAMBIA',
              'bounds': (21.0, 35.0, -20.0, -7.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'zm', 'name': 'WESTERN SAMOA',
              'bounds': (170.5, 173.5, -15.0, -13.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'zr', 'name': 'ZAIRE',
              'bounds': (12.0, 31.6, -14.0, 6.0),
              'proj': ccrs.PlateCarree()},
             {'area': 'zw', 'name': 'ZIMBABWE',
              'bounds': (25.0, 34.0, -22.9, -15.5),
              'proj': ccrs.PlateCarree()}]

df = pd.DataFrame(area_data)
df.set_index('area', inplace=True)

with exporter:
    areas = df
