on:
  pull_request:
    paths:
      - '.github/**'

permissions:
  contents: read

jobs:
  verify-pinned-actions:
    name: Verify Pinned Actions
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: unidata/pinned-actions-verifier@a7df1b8ac192ab2903c6b04b64827da1925aac69 # v1.0.1
